# Generated by Django 5.2.9 on 2025-12-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_solicitacaoreparo_imagemreparo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao_proposta', models.TextField(blank=True)),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='banco.solicitacaoreparo')),
            ],
            options={
                'verbose_name': 'Interesse em Solicitação',
                'verbose_name_plural': 'Interesses em Solicitações',
                'ordering': ['-data_interesse'],
                'unique_together': {('solicitacao', 'escritorio')},
            },
        ),
    ]
